

doctrine:
    dbal:
        default_connection: conn_mysql
        connections:
            conn_mysql:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                url: '%env(resolve:MYSQL_DATABASE_URL)%'
