

doctrine:
    dbal:
        default_connection: conn_mysql
        connections:
            conn_mysql:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                url: '%env(resolve:MYSQL_DATABASE_URL)%'
            conn_pgsql:
                driver: 'pdo_pqsql'
                server_version: '10.1'
                charset: utf8
                url: '%env(resolve:PGSQL_DATABASE_URL)%'
            conn_sqlite:
                driver: 'sqlite'
                server_version: '3'
                charset: utf8
                url: '%env(resolve:SQLITE_DATABASE_URL)%'
